In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

In [3]:
type(list)

list

In [4]:
n1 = np.array(list)
type(n1)

numpy.ndarray

In [5]:
list2 = [[1,2,3,4,5], [5,4,3,2,1]]

In [6]:
n2 = np.array(list2)
n2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

# ***Intialiazation Of an numpy array***

In [7]:
n3 = np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# ***Intialiazation Of an numpy array using fix value***

In [8]:
n4 = np.full((5,5), 10)
n4

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# ***Intialiazation Of an numpy array within range***

In [9]:
n5 = np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
n6 = np.arange(10,200,5)
n6

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195])

# ***Intialiazation Of an numpy array using random numbers***

In [11]:
# Getting random numbers np.random.randint(starting no. ,ending no. ,how many no. u want )

In [12]:
n7 = np.random.randint(1,100,5)
n7

array([31, 22, 32, 45, 48])

In [13]:
#checking the shape of numpy arrays result=> (row,col)

In [14]:
n8 = np.array([[1,2,3,4,5],[5,4,3,2,1]])
n8.shape

(2, 5)

In [15]:
n8.shape = (5,2)
n8

array([[1, 2],
       [3, 4],
       [5, 5],
       [4, 3],
       [2, 1]])

# ***Joining two numpy arrays***

In [16]:
# Three ways:
#1.vstack() - vertically
#2.hstack() - horizontally
#3.column_stack() - column

In [17]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([5,4,3,2,1])
n3 = np.vstack((n1,n2))
n3

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [18]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([5,4,3,2,1])
n3 = np.hstack((n1,n2))
n3

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [19]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([5,4,3,2,1])
n3 = np.column_stack((n1,n2))
n3

array([[1, 5],
       [2, 4],
       [3, 3],
       [4, 2],
       [5, 1]])

In [20]:
# Numpy operations - intersection & difference
#intersection - returns common elements in both arrays
#difference - returns unique elements in ar1 that are not in ar2

In [21]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([4,5,6,7,8,9])
n3 = np.setdiff1d(n1,n2)
n3

array([1, 2, 3])

In [22]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([4,5,6,7,8,9])
n3 = np.intersect1d(n1,n2)
n3

array([4, 5, 6])

# ***Addition of Numpy Arrays***

In [23]:
#np.sum([ _, _], axis=0 => col)
#np.sum([ _, _], axis=1 => row)

In [24]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([4,5,6,7,8,9])
n3 = np.sum([n1,n2])
n3

60

In [25]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([4,5,6,7,8,9])
n3 = np.sum([n1,n2],axis = 0)
n3

array([ 5,  7,  9, 11, 13, 15])

In [26]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([4,5,6,7,8,9])
n3 = np.sum([n1,n2], axis = 1)
n3

array([21, 39])

In [27]:
#Arithmetic Operations

In [28]:
#Addition
